name: Job Level Concurrency test
on:
  pull_request:

  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: sleep 10
        run: sleep 10
  job_2:
    runs-on: ubuntu-latest
    needs: [job_1]
    concurrency: job_2
    steps:
      - name: sleep 100
      - run: sleep 100
